apiVersion: v1
kind: Secret
metadata:
  name: s3creds
  annotations:
     # replace with your s3 endpoint e.g minio-service.kubeflow:9000
     serving.kserve.io/s3-endpoint: s3.ru-1.storage.selcloud.ru:443
     # by default 1, if testing with minio you can set to 0
     serving.kserve.io/s3-usehttps: "1"
     serving.kserve.io/s3-region: "ru-1"
     # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials
     serving.kserve.io/s3-useanoncredential: "false"
type: Opaque
# use `stringData` for raw credential string or `data` for base64 encoded string
stringData:
  AWS_ACCESS_KEY_ID: "<AWS_ACCESS_KEY_ID>"
  AWS_SECRET_ACCESS_KEY: "<AWS_SECRET_ACCESS_KEY>"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
secrets:
- name: s3creds